### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #37: Write a CONTRIBUTING.md file
Simple instructions about what's expected of contributors and of maintainers, mention of [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/), and other items I might be overlooking at the moment.

### PR DESCRIPTION
**Pull request by waldyrious**
fixes #37.

### CODE REVIEW

**Comment by waldyrious** [comment]
Glad you like it :) I'll merge then.

**Comment by waldyrious** [comment]
@Jan-Ka one question: were you automatically subscribed to the notifications for this repository (i.e. set to "watching" status) once you joined as a contributor, or did you change that yourself? If it has to be done manually, we might want to add that to the "Instructions for maintainers" section.

**Comment by Jan-Ka** [comment]
It did that automatically. Pretty sure I did nothing regarding that beside accepting the invitation as contributor.

**Comment by waldyrious** [comment]
Cool, one less thing to add to the document :) the longer it gets, the less likely people are to actually read it.

**Pull request merged**
